name: Publish to PyPI

permissions:
    contents: read

on:
  release:
    types: [published]  # Trigger only when a GitHub Release is published.

jobs:
  publish:
    name: Build and Publish
    # don't run this job in sync'd clones
    if: github.repository == 'cognizant-ai-lab/neuro-san'
    runs-on: ubuntu-latest
    environment: pypi  # Match this to your configured GitHub Environment.
    permissions:
      id-token: write  # Mandatory for PyPi Trusted Publishing

    steps:
      # v4.3.1
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      # 1.0.0
      - name: Setup Python environment
        uses: cognizant-ai-lab/build-common/actions/setup-python-env@455db3cc40e9ed6a0fb9bbaf8188888c1ae315c2
        with:
          python-version: '3.10'
          requirements-file: ''
          requirements-build-file: ''
          install-extras: 'build'

      - name: Build wheel and sdist
        run: python -m build

      # v1.9.0
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0

      # 1.0.0
      - name: Notify Slack
        if: ${{ !cancelled() }}
        uses: cognizant-ai-lab/build-common/actions/slack-notify@455db3cc40e9ed6a0fb9bbaf8188888c1ae315c2
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
